# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b79277068f97282e803ddd979db00bf67700153e4facb80c1cef48a1174dafcc44e34d935b43c58f5fd5e09a63f4d0c5c32e944bbf654fea8c5957bbdf7c5a3

test:
  secret_key_base: fdf1587b6d8206f62ab77e62ba291c0d56d9478cb47423b90c49774a01855708b96b7229afab717399b54d343ff9ae11318c9cdf9e801f5fa29d05bfafc550bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
